In [18]:
import bq_helper
import pandas as pd

In [19]:
traffic_data = bq_helper.BigQueryHelper(active_project="bigquery-public-data",
                                   dataset_name="nhtsa_traffic_fatalities")

In [20]:
traffic_data.list_tables()

['accident_2015',
 'accident_2016',
 'cevent_2015',
 'cevent_2016',
 'damage_2015',
 'damage_2016',
 'distract_2015',
 'distract_2016',
 'drimpair_2015',
 'drimpair_2016',
 'factor_2015',
 'factor_2016',
 'maneuver_2015',
 'maneuver_2016',
 'nmcrash_2015',
 'nmcrash_2016',
 'nmimpair_2015',
 'nmimpair_2016',
 'nmprior_2015',
 'nmprior_2016',
 'parkwork_2015',
 'parkwork_2016',
 'pbtype_2015',
 'pbtype_2016',
 'person_2015',
 'person_2016',
 'safetyeq_2015',
 'safetyeq_2016',
 'vehicle_2015',
 'vehicle_2016',
 'vevent_2015',
 'vevent_2016',
 'vindecode_2015',
 'vindecode_2016',
 'violatn_2015',
 'violatn_2016',
 'vision_2015',
 'vision_2016',
 'vsoe_2015',
 'vsoe_2016']

In [21]:
traffic_data.head('drimpair_2016')

,state_number,consecutive_number,vehicle_number,condition_impairment_at_time_of_crash_driver,condition_impairment_at_time_of_crash_driver_name
0,39,390812,1,0,None/Apparently Normal
1,39,390480,1,0,None/Apparently Normal
2,40,400031,1,0,None/Apparently Normal
3,40,400169,1,0,None/Apparently Normal
4,39,390857,1,0,None/Apparently Normal

In [22]:
 traffic_data.head('distract_2016')

,state_number,consecutive_number,vehicle_number,driver_distracted_by,driver_distracted_by_name
0,1,10409,1,0,Not Distracted
1,1,10497,1,0,Not Distracted
2,1,10300,1,0,Not Distracted
3,1,10039,1,0,Not Distracted
4,1,10008,1,0,Not Distracted

In [23]:
traffic_data.head('vehicle_2016')

,state_number,consecutive_number,vehicle_number,number_of_motor_vehicles_in_transport_mvit,number_of_occupants,day_of_crash,month_of_crash,hour_of_crash,minute_of_crash,first_harmful_event,...,critical_event_precrash_name,attempted_avoidance_maneuver,attempted_avoidance_maneuver_name,pre_impact_stability,pre_impact_location,crash_type,crash_type_name,fatalities_in_vehicle,driver_drinking,timestamp_of_crash
0,6,61700,1,1,2,7,8,2,36,5,...,Other Critical Precrash Event,1,No Avoidance Maneuver,Tracking,3,0,No Impact,1,Drinking,2016-08-07 02:36:00+00:00
1,32,320154,1,1,1,19,7,9,45,1,...,Over the Lane Line on Right Side of Travel Lane,16,,Skidding Laterally â€“ Counterclockwise Rotation,2,98,"MISCELLANEOUS, CONFIGURATION M: BACKING, ETC.,...",1,No Drinking,2016-07-19 09:45:00+00:00
2,17,171005,1,1,2,28,7,18,40,7,...,Other Critical Precrash Event,99,Unknown,Precrash Stability Unknown,1,0,No Impact,1,No Drinking,2016-07-28 18:40:00+00:00
3,40,400018,1,1,1,12,1,7,10,10,...,Object in Road,1,No Avoidance Maneuver,Tracking,1,15,"SINGLE DRIVER, CONFIGURATION C: FORWARD IMPACT...",1,No Drinking,2016-01-12 07:10:00+00:00
4,48,480672,1,1,2,20,3,18,10,5,...,Other Critical Precrash Event,99,Unknown,Tracking,1,0,No Impact,1,No Drinking,2016-03-20 18:10:00+00:00

In [24]:
 list(traffic_data.head('vehicle_2016').columns)

['state_number',
 'consecutive_number',
 'vehicle_number',
 'number_of_motor_vehicles_in_transport_mvit',
 'number_of_occupants',
 'day_of_crash',
 'month_of_crash',
 'hour_of_crash',
 'minute_of_crash',
 'first_harmful_event',
 'first_harmful_event_name',
 'manner_of_collision',
 'unit_type',
 'hit_and_run',
 'registration_state',
 'registration_state_name',
 'registered_vehicle_owner',
 'registered_vehicle_owner_name',
 'vehicle_make',
 'vehicle_make_name',
 'vehicle_model',
 'make_model_combined',
 'body_type',
 'body_type_name',
 'vehicle_model_year',
 'vehicle_identification_number_vin',
 'vin_character_1',
 'vin_character_2',
 'vin_character_3',
 'vin_character_4',
 'vin_character_5',
 'vin_character_6',
 'vin_character_7',
 'vin_character_8',
 'vin_character_9',
 'vin_character_10',
 'vin_character_11',
 'vin_character_12',
 'vehicle_trailing',
 'jackknife',
 'mcid_issuing_authority',
 'mcid_identification_number',
 'motor_carrier_identification_number_mcid',
 'gross_vehicle_weight_rating',
 'vehicle_configuration',
 'vehicle_configuration_name',
 'cargo_body_type',
 'cargo_body_type_name',
 'hazardous_material_involvement',
 'hazardous_material_placard',
 'hazardous_material_identification_number',
 'hazardous_material_class_number',
 'release_of_hazardous_material_from_the_cargo_compartment',
 'bus_use',
 'special_use',
 'special_use_name',
 'emergency_motor_vehicle_use',
 'travel_speed',
 'underride_override',
 'rollover',
 'location_of_rollover',
 'initial_contact_point',
 'extent_of_damage',
 'vehicle_removal',
 'most_harmful_event',
 'related_factors_vehicle_level_1',
 'related_factors_vehicle_level_2',
 'fire_occurrence',
 'driver_presence',
 'drivers_license_state',
 'drivers_zip_code',
 'non_cdl_license_status',
 'non_cdl_license_type',
 'commercial_motor_vehicle_license_status',
 'compliance_with_cdl_endorsements',
 'license_compliance_with_class_of_vehicle',
 'compliance_with_license_restrictions',
 'driver_height',
 'driver_weight',
 'previous_recorded_crashes',
 'previous_recorded_suspensions_and_revocations',
 'previous_dwi_convictions',
 'previous_speeding_convictions',
 'previous_other_moving_violation_convictions',
 'month_of_first_crash_suspension_or_conviction',
 'year_of_first_crash_suspension_or_conviction',
 'month_of_last_crash_suspension_or_conviction',
 'year_of_last_crash_suspension_or_conviction',
 'speeding_related',
 'related_factors_driver_level_1',
 'related_factors_driver_level_2',
 'related_factors_driver_level_3',
 'related_factors_driver_level_4',
 'trafficway_description',
 'total_lanes_in_roadway',
 'speed_limit',
 'roadway_alignment',
 'roadway_grade',
 'roadway_surface_type',
 'roadway_surface_condition',
 'roadway_surface_condition_name',
 'traffic_control_device',
 'traffic_control_device_functioning',
 'pre_event_movement_prior_to_recognition_of_critical_event',
 'critical_event_precrash',
 'critical_event_precrash_name',
 'attempted_avoidance_maneuver',
 'attempted_avoidance_maneuver_name',
 'pre_impact_stability',
 'pre_impact_location',
 'crash_type',
 'crash_type_name',
 'fatalities_in_vehicle',
 'driver_drinking',
 'timestamp_of_crash']

In [25]:
traffic_data.head('vehicle_2016')[['body_type_name',
                                    'vehicle_make_name',
                                    'vehicle_model_year',
                                    'travel_speed',
                                    'previous_dwi_convictions',
                                    'previous_speeding_convictions',
                                    'previous_other_moving_violation_convictions',
                                    'driver_drinking',]]

,body_type_name,vehicle_make_name,vehicle_model_year,travel_speed,previous_dwi_convictions,previous_speeding_convictions,previous_other_moving_violation_convictions,driver_drinking
0,2-Door Sedan/Hardtop/Coupe,Dodge,2013,998,99,99,99,Drinking
1,Motorcycle,Yamaha,2015,28,0,0,2,No Drinking
2,Golf Cart (Since 2012),Other Make\nAuto-Union-DKW\nCarpenter\nCollins...,9999,998,99,99,99,No Drinking
3,Farm Equipment Other Than Trucks,Other Make\nAuto-Union-DKW\nCarpenter\nCollins...,2013,998,0,1,2,No Drinking
4,Farm Equipment Other Than Trucks,Other Make\nAuto-Union-DKW\nCarpenter\nCollins...,1999,998,0,2,1,No Drinking

In [26]:
traffic_data.head('accident_2016')

,state_number,state_name,consecutive_number,number_of_vehicle_forms_submitted_all,number_of_motor_vehicles_in_transport_mvit,number_of_parked_working_vehicles,number_of_forms_submitted_for_persons_not_in_motor_vehicles,number_of_persons_not_in_motor_vehicles_in_transport_mvit,number_of_persons_in_motor_vehicles_in_transport_mvit,number_of_forms_submitted_for_persons_in_motor_vehicles,...,minute_of_ems_arrival_at_hospital,related_factors_crash_level_1,related_factors_crash_level_1_name,related_factors_crash_level_2,related_factors_crash_level_2_name,related_factors_crash_level_3,related_factors_crash_level_3_name,number_of_fatalities,number_of_drunk_drivers,timestamp_of_crash
0,19,Iowa,190192,1,1,0,0,0,1,1,...,88,0,None,0,None,0,None,1,0,2016-08-06 00:55:00+00:00
1,19,Iowa,190028,1,1,0,0,0,6,6,...,99,0,None,0,None,0,None,1,0,2016-02-13 14:16:00+00:00
2,19,Iowa,190038,1,1,0,0,0,5,5,...,99,0,None,0,None,0,None,1,0,2016-03-05 21:38:00+00:00
3,19,Iowa,190146,1,1,0,0,0,1,1,...,99,0,None,0,None,0,None,1,0,2016-06-24 18:47:00+00:00
4,19,Iowa,190043,1,1,0,0,0,1,1,...,45,0,None,0,None,0,None,1,0,2016-03-16 15:18:00+00:00

In [27]:
list(traffic_data.head('accident_2016').columns)

['state_number',
 'state_name',
 'consecutive_number',
 'number_of_vehicle_forms_submitted_all',
 'number_of_motor_vehicles_in_transport_mvit',
 'number_of_parked_working_vehicles',
 'number_of_forms_submitted_for_persons_not_in_motor_vehicles',
 'number_of_persons_not_in_motor_vehicles_in_transport_mvit',
 'number_of_persons_in_motor_vehicles_in_transport_mvit',
 'number_of_forms_submitted_for_persons_in_motor_vehicles',
 'county',
 'city',
 'day_of_crash',
 'month_of_crash',
 'year_of_crash',
 'day_of_week',
 'hour_of_crash',
 'minute_of_crash',
 'national_highway_system',
 'land_use',
 'land_use_name',
 'functional_system',
 'functional_system_name',
 'ownership',
 'ownership_name',
 'route_signing',
 'route_signing_name',
 'trafficway_identifier',
 'trafficway_identifier_2',
 'milepoint',
 'latitude',
 'longitude',
 'special_jurisdiction',
 'special_jurisdiction_name',
 'first_harmful_event',
 'first_harmful_event_name',
 'manner_of_collision',
 'manner_of_collision_name',
 'relation_to_junction_within_interchange_area',
 'relation_to_junction_specific_location',
 'relation_to_junction_specific_location_name',
 'type_of_intersection',
 'work_zone',
 'relation_to_trafficway',
 'relation_to_trafficway_name',
 'light_condition',
 'light_condition_name',
 'atmospheric_conditions_1',
 'atmospheric_conditions_1_name',
 'atmospheric_conditions_2',
 'atmospheric_conditions_2_name',
 'atmospheric_conditions',
 'atmospheric_conditions_name',
 'school_bus_related',
 'rail_grade_crossing_identifier',
 'hour_of_notification',
 'minute_of_notification',
 'hour_of_arrival_at_scene',
 'minute_of_arrival_at_scene',
 'hour_of_ems_arrival_at_hospital',
 'minute_of_ems_arrival_at_hospital',
 'related_factors_crash_level_1',
 'related_factors_crash_level_1_name',
 'related_factors_crash_level_2',
 'related_factors_crash_level_2_name',
 'related_factors_crash_level_3',
 'related_factors_crash_level_3_name',
 'number_of_fatalities',
 'number_of_drunk_drivers',
 'timestamp_of_crash']

In [28]:
traffic_data.head('accident_2016')[['number_of_drunk_drivers', 
                                    'related_factors_crash_level_1_name',
                                    'related_factors_crash_level_2_name',
                                    'school_bus_related',
                                    'latitude',
                                    'longitude',
                                    'state_name',]]

,number_of_drunk_drivers,related_factors_crash_level_1_name,related_factors_crash_level_2_name,school_bus_related,latitude,longitude,state_name
0,0,None,None,No,43.466419,-95.076206,Iowa
1,0,None,None,No,42.544686,-94.060925,Iowa
2,0,None,None,No,42.503764,-96.439783,Iowa
3,0,None,None,No,42.471000,-91.321406,Iowa
4,0,None,None,No,41.648014,-90.568000,Iowa

In [38]:
join_accidents_and_vehicles = """
SELECT a.consecutive_number AS a_consecutive_number, a.latitude, a.longitude, 
        a.number_of_drunk_drivers, a.city, a.timestamp_of_crash,
        a.number_of_fatalities, a.related_factors_crash_level_1_name,
        a.related_factors_crash_level_2_name, a.related_factors_crash_level_3_name,
        v.consecutive_number AS v_consecutive_number,
        v.vehicle_make_name, v.vehicle_model_year, v.travel_speed,
        v.previous_dwi_convictions, v.previous_speeding_convictions,
        v.previous_other_moving_violation_convictions, v.driver_drinking
FROM `bigquery-public-data.nhtsa_traffic_fatalities.accident_2016` a INNER JOIN `bigquery-public-data.nhtsa_traffic_fatalities.vehicle_2016` v
    ON a.consecutive_number = v.consecutive_number
"""

In [39]:
traffic_data.estimate_query_size(join_accidents_and_vehicles)

0.006117518991231918

In [40]:
a_v_2016 = traffic_data.query_to_pandas_safe(join_accidents_and_vehicles)

,a_consecutive_number,latitude,longitude,number_of_drunk_drivers,city,timestamp_of_crash,number_of_fatalities,related_factors_crash_level_1_name,related_factors_crash_level_2_name,related_factors_crash_level_3_name,v_consecutive_number,vehicle_make_name,vehicle_model_year,travel_speed,previous_dwi_convictions,previous_speeding_convictions,previous_other_moving_violation_convictions,driver_drinking
0,190192,43.466419,-95.076206,0,0,2016-08-06 00:55:00+00:00,1,None,None,None,190192,Pontiac,1999,998,1,0,1,No Drinking
1,190028,42.544686,-94.060925,0,0,2016-02-13 14:16:00+00:00,1,None,None,None,190028,Chevrolet,2003,998,0,0,0,No Drinking
2,190146,42.471000,-91.321406,0,0,2016-06-24 18:47:00+00:00,1,None,None,None,190146,Other Make\nAuto-Union-DKW\nCarpenter\nCollins...,2013,998,0,0,0,No Drinking
3,190042,41.690228,-95.843192,0,0,2016-03-14 13:26:00+00:00,1,None,None,None,190042,Other Make\nAuto-Union-DKW\nCarpenter\nCollins...,2010,998,0,0,0,No Drinking
4,190340,41.423617,-92.651250,0,0,2016-12-15 17:02:00+00:00,1,None,None,None,190340,Saturn,2004,998,0,0,0,No Drinking
5,190094,41.433272,-95.751250,0,0,2016-05-07 16:17:00+00:00,1,None,None,None,190094,Harley-Davidson,2009,998,0,0,0,No Drinking
6,190003,40.711489,-94.346800,0,0,2016-01-10 03:00:00+00:00,1,None,None,None,190003,GMC,2002,998,0,0,0,No Drinking
7,190101,40.648450,-92.847817,0,0,2016-05-12 13:35:00+00:00,1,None,None,None,190101,Honda,2015,998,0,0,0,No Drinking
8,190270,41.849086,-95.020514,0,0,2016-10-24 17:19:00+00:00,1,None,None,None,190270,Honda,2004,998,0,0,0,No Drinking
9,190148,43.432828,-96.110106,0,0,2016-06-25 16:23:00+00:00,1,None,None,None,190148,Ford,1992,998,0,0,0,No Drinking
10,190018,42.449197,-93.860783,0,0,2016-01-08 18:34:00+00:00,1,None,None,None,190018,Pontiac,2006,998,0,0,0,No Drinking
11,190186,42.447978,-93.225611,0,0,2016-07-11 03:25:00+00:00,1,None,None,None,190186,Freightliner,2002,998,0,0,0,No Drinking
12,190186,42.447978,-93.225611,0,0,2016-07-11 03:25:00+00:00,1,None,None,None,190186,Volvo,2007,998,0,0,0,No Drinking
13,190227,40.906014,-91.549853,0,0,2016-09-15 14:20:00+00:00,1,None,None,None,190227,Other Make\nAuto-Union-DKW\nCarpenter\nCollins...,2015,998,0,1,0,No Drinking
14,190178,43.123150,-96.294292,0,0,2016-07-27 22:15:00+00:00,1,None,None,None,190178,Chevrolet,2008,998,99,99,99,No Drinking
15,190147,42.704328,-91.075694,0,0,2016-06-25 12:38:00+00:00,1,None,None,None,190147,Honda,1996,998,0,0,0,No Drinking
16,190302,41.496786,-94.713700,0,0,2016-11-05 13:10:00+00:00,1,None,None,None,190302,Buick/Opel,2004,998,0,0,0,No Drinking
17,190006,41.933458,-95.922389,0,0,2016-01-15 07:36:00+00:00,1,None,None,None,190006,Chevrolet,2001,998,0,0,0,No Drinking
18,190060,40.856058,-94.497156,0,0,2016-03-22 16:12:00+00:00,1,None,None,None,190060,Kia,2005,998,0,0,0,No Drinking
19,190189,42.013836,-96.121669,0,0,2016-08-05 04:00:00+00:00,1,None,None,None,190189,Harley-Davidson,2006,998,0,0,0,No Drinking
20,190107,41.190125,-94.453033,0,0,2016-05-20 19:57:00+00:00,1,None,None,None,190107,Ford,1995,998,0,4,1,No Drinking
21,190228,41.838433,-91.977017,0,0,2016-09-16 21:35:00+00:00,1,None,None,None,190228,Other Make\nAuto-Union-DKW\nCarpenter\nCollins...,9999,998,2,1,3,No Drinking
22,190051,41.316172,-94.303697,0,0,2016-03-06 07:15:00+00:00,1,None,None,None,190051,Chrysler,2000,998,0,1,1,No Drinking
23,190244,42.090344,-91.692097,0,0,2016-09-23 17:03:00+00:00,1,None,None,None,190244,Ford,1992,998,0,0,0,No Drinking
24,190058,41.148822,-92.122564,0,0,2016-04-13 08:40:00+00:00,1,None,None,None,190058,Mercury,1999,998,0,0,0,No Drinking
25,190352,42.316931,-90.934383,0,0,2016-12-26 06:49:00+00:00,1,None,None,None,190352,Chevrolet,2002,998,0,0,0,No Drinking
26,190274,42.903897,-91.656128,0,0,2016-10-11 06:13:00+00:00,1,None,None,None,190274,Harley-Davidson,2004,998,0,4,3,No Drinking
27,190144,41.496297,-94.528511,0,0,2016-06-24 10:25:00+00:00,1,None,None,None,190144,Freightliner,2008,998,0,2,0,No Drinking
28,190202,40.630914,-92.964811,0,0,2016-08-19 21:00:00+00:00,1,None,None,None,190202,Dodge,1996,998,1,1,0,No Drinking
29,190138,42.638667,-91.215067,0,0,2016-06-19 08:57:00+00:00,1,None,None,None,190138,Harley-Davidson,2004,998,0,0,0,No Drinking
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52201,360809,99.999900,999.999900,0,5630,2016-11-21 20:09:00+00:00,1,None,None,None,360809,Peterbilt,2012,60,0,0,3,No Drinking
52202,360809,99.999900,999.999900,0,5630,2016-11-21 20:09:00+00:00,1,None,None,None,360809,Toyota,2006,999,0,1,2,No Drinking
52203,360861,42.908678,-76.839447,0,5630,2016-11-23 16:11:00+00:00,1,None,None,None,360861,Ford,2003,30,0,0,0,No Drinking
52204,290590,37.935333,-91.747969,0,6910,2016-09-11 10:57:00+00:00,1,None,None,None,290590,Kia,2012,998,0,0,0,No Drinking
52205,290590,37.935333,-91.747969,0,6910,2016-09-11 10:57:00+00:00,1,None,None,None,290590,Dodge,2006,998,0,0,0,No Drinking
52206,290556,37.960556,-91.773583,0,6910,2016-09-08 20:44:00+00:00,1,None,None,None,290556,Kenworth,2015,46,0,1,0,No Drinking
52207,290374,37.951906,-91.788261,0,6910,2016-06-26 09:24:00+00:00,1,None,None,None,290374,Mitsubishi,1998,998,0,1,0,No Drinking
52208,270185,48.107978,-96.186925,0,6910,2016-07-18 17:53:00+00:00,1,None,None,None,270185,Dodge,1998,998,0,0,0,No Drinking
52209,420249,40.370633,-75.482761,1,6910,2016-04-02 00:45:00+00:00,1,Police-Pursuit-Involved (Since 1994),None,None,420249,Volkswagen,2001,105,0,0,0,Drinking
52210,290312,37.786028,-92.255444,0,8190,2016-06-08 07:12:00+00:00,1,None,None,None,290312,Chevrolet,2001,62,0,0,0,No Drinking
52211,290312,37.786028,-92.255444,0,8190,2016-06-08 07:12:00+00:00,1,None,None,None,290312,Chevrolet,2010,62,0,0,0,No Drinking
52212,390209,40.058564,-84.246686,1,8190,2016-02-29 13:14:00+00:00,1,None,None,None,390209,Harley-Davidson,2008,998,0,1,0,Drinking
52213,390209,40.058564,-84.246686,1,8190,2016-02-29 13:14:00+00:00,1,None,None,None,390209,Honda,2004,15,0,0,0,No Drinking
52214,220707,29.919528,-90.200111,0,255,2016-12-25 14:25:00+00:00,1,None,None,None,220707,Dodge,2001,10,0,0,3,No Drinking
52215,220707,29.919528,-90.200111,0,255,2016-12-25 14:25:00+00:00,1,None,None,None,220707,Honda,2009,35,0,0,0,No Drinking
52216,250203,42.565828,-70.947042,0,255,2016-09-13 06:57:00+00:00,1,None,None,None,250203,Honda,2010,998,0,1,3,No Drinking
52217,250359,42.587228,-70.966481,0,255,2016-11-21 18:00:00+00:00,1,None,None,None,250359,Freightliner,2016,998,99,99,99,No Drinking
52218,250359,42.587228,-70.966481,0,255,2016-11-21 18:00:00+00:00,1,None,None,None,250359,Hyundai,2005,998,0,0,0,No Drinking
52219,250317,42.550556,-70.946867,0,255,2016-05-27 00:00:00+00:00,1,Unknown,Unknown,Unknown,250317,Datsun/Nissan,2008,998,0,0,0,No Drinking
52220,250317,42.550556,-70.946867,0,255,2016-05-27 00:00:00+00:00,1,Unknown,Unknown,Unknown,250317,Datsun/Nissan,2006,998,0,0,0,No Drinking
52221,330062,42.909094,-71.085108,0,255,2016-07-17 09:35:00+00:00,1,None,None,None,330062,Ford,2005,998,0,0,0,No Drinking
52222,250089,42.382817,-71.411647,0,1279,2016-04-06 15:44:00+00:00,1,None,None,None,250089,Cadillac,2008,998,0,0,0,No Drinking
52223,250089,42.382817,-71.411647,0,1279,2016-04-06 15:44:00+00:00,1,None,None,None,250089,Freightliner,2015,998,0,1,1,No Drinking
52224,250003,41.661558,-70.201722,0,1535,2016-01-06 00:00:00+00:00,1,None,None,None,250003,Honda,2000,998,0,0,0,No Drinking
52225,250234,41.660789,-70.243775,1,1535,2016-10-01 22:40:00+00:00,2,None,None,None,250234,GMC,2004,998,0,1,0,Drinking
52226,250234,41.660789,-70.243775,1,1535,2016-10-01 22:40:00+00:00,2,None,None,None,250234,Audi,2012,998,0,0,0,No Drinking
52227,60440,33.957067,-117.922067,0,1791,2016-03-26 18:40:00+00:00,1,None,None,None,60440,Honda,2009,999,0,0,0,No Drinking
52228,63007,33.950783,-117.927500,0,1791,2016-10-01 02:50:00+00:00,1,None,None,None,63007,Toyota,2007,998,0,0,0,No Drinking
52229,63007,33.950783,-117.927500,0,1791,2016-10-01 02:50:00+00:00,1,None,None,None,63007,Chevrolet,2014,998,0,0,0,No Drinking
52230,170473,39.273628,-90.199933,1,7423,2016-06-25 20:00:00+00:00,1,None,None,None,170473,Ford,1998,998,0,0,0,Drinking

In [ ]:
a_v_2016.to_csv('vehicle_and_accident_data_2016.csv')